// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateEnquiry(ctx context.Context, arg CreateEnquiryParams) error
	GetEnquiries(ctx context.Context, createdAt pgtype.Timestamptz) ([]GetEnquiriesRow, error)
}

var _ Querier = (*Queries)(nil)
