// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateEnquiry(ctx context.Context, arg CreateEnquiryParams) error
	GetEnquiries(ctx context.Context) ([]GetEnquiriesRow, error)
}

var _ Querier = (*Queries)(nil)
