// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnquiry = `-- name: CreateEnquiry :exec
INSERT INTO enquiries (name, phone, email, message)
VALUES ($1, $2, $3, $4)
    RETURNING id, created_at
`

type CreateEnquiryParams struct {
	Name    string
	Phone   string
	Email   pgtype.Text
	Message json.RawMessage
}

func (q *Queries) CreateEnquiry(ctx context.Context, arg CreateEnquiryParams) error {
	_, err := q.db.Exec(ctx, createEnquiry,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Message,
	)
	return err
}

const getEnquiries = `-- name: GetEnquiries :many
SELECT id, name, phone, email, message, created_at
FROM enquiries
ORDER BY created_at DESC
`

type GetEnquiriesRow struct {
	ID        int64
	Name      string
	Phone     string
	Email     pgtype.Text
	Message   json.RawMessage
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetEnquiries(ctx context.Context) ([]GetEnquiriesRow, error) {
	rows, err := q.db.Query(ctx, getEnquiries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEnquiriesRow{}
	for rows.Next() {
		var i GetEnquiriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
